/**
 * ReleaseRadar — Data Layer
 * ---------------------------------------------------------
 * This file simulates an API response. Every consumer in the
 * app talks to the functions at the bottom of this file
 * (getAllItems, getItemById, etc.) instead of touching RAW_ITEMS
 * directly. When a real backend exists, replace the body of
 * fetchItems() with an actual `fetch('/api/items')` call that
 * resolves to the same shape and nothing else in the app needs
 * to change.
 *
 * Item shape:
 * {
 *   id: string,
 *   title: string,
 *   category: 'game' | 'movie' | 'tv' | 'animation',
 *   genres: string[],
 *   releaseDate: ISOString,
 *   studio: string,
 *   description: string,
 *   synopsis: string,
 *   platforms: string[] | null,   // games only
 *   anticipated: boolean,
 *   hype: number,                 // 0-100, drives "Most Anticipated" ordering
 *   rating: number | null,        // critic/user score out of 10, null if unreleased
 * }
 */

const RAW_ITEMS = [
  // ---------------- GAMES ----------------
  {
    id: "game-nightfall-protocol",
    title: "Nightfall Protocol",
    category: "game",
    genres: ["Action", "Stealth"],
    releaseDate: "2026-08-18T00:00:00-04:00",
    studio: "Voidline Studios",
    description: "A silent operative unravels a conspiracy that never sleeps.",
    synopsis: "Set in the perpetually dark megacity of Ostrava-9, Nightfall Protocol casts you as an off-book operative hunting a rogue AI that has taken control of the city's surveillance grid. Every shadow is cover, every light is a threat. Chain stealth takedowns, hack security drones mid-sprint, and make irreversible choices that reshape the final act.",
    platforms: ["PS5", "Xbox Series X|S", "PC"],
    anticipated: true,
    hype: 88,
    rating: 8.7,
  },
  {
    id: "game-ashen-throne",
    title: "Ashen Throne",
    category: "game",
    genres: ["RPG", "Fantasy"],
    releaseDate: "2026-08-21T00:00:00-04:00",
    studio: "Greywatch Interactive",
    description: "A shattered kingdom, a cursed crown, and a war only you can end.",
    synopsis: "Ashen Throne is an open-world RPG set in the ashlands of Virendell, a kingdom left in ruin after a magical cataclysm. Build your bloodline, forge alliances between five warring houses, and wield ash-magic pulled directly from the ruins of the old world. Choices ripple across a living political simulation that remembers everything you do.",
    platforms: ["PS5", "Xbox Series X|S", "PC", "Switch 2"],
    anticipated: false,
    hype: 74,
    rating: null,
  },
  {
    id: "game-quantum-drift",
    title: "Quantum Drift",
    category: "game",
    genres: ["Racing", "Arcade"],
    releaseDate: "2026-09-10T00:00:00-04:00",
    studio: "Lumen Forge",
    description: "Physics-bending street racing across cities that fold in on themselves.",
    synopsis: "Race through cityscapes that literally rearrange themselves mid-lap. Quantum Drift blends arcade handling with a rewind-and-remix track system, letting you and up to 11 rivals reshape the circuit in real time. Fully cross-platform, with a live seasonal track rotation built on the same engine as the shipping build.",
    platforms: ["PS5", "Xbox Series X|S", "PC", "Switch 2"],
    anticipated: false,
    hype: 61,
    rating: null,
  },
  {
    id: "game-iron-sanctum",
    title: "Iron Sanctum",
    category: "game",
    genres: ["Mecha", "Shooter"],
    releaseDate: "2026-10-02T00:00:00-04:00",
    studio: "Redline Collective",
    description: "Pilot a war-forged mech through a siege that never officially ended.",
    synopsis: "Iron Sanctum drops you into the cockpit of a customizable war-mech defending the last free sanctum on a planet that surrendered decades ago. Deep loadout customization meets tight, weighty third-person combat, with a co-op campaign built for two pilots sharing one chassis.",
    platforms: ["PS5", "Xbox Series X|S", "PC"],
    anticipated: false,
    hype: 55,
    rating: null,
  },
  {
    id: "game-wraithbound",
    title: "Wraithbound",
    category: "game",
    genres: ["Souls-like", "Dark Fantasy"],
    releaseDate: "2026-11-14T00:00:00-05:00",
    studio: "Hollow Anvil",
    description: "Bound to a wraith you cannot kill, in a world that already has.",
    synopsis: "You wake bound to a wraith that whispers memories that aren't yours. Wraithbound is a punishing action-RPG where every death rewrites a fragment of the world's history, and the wraith's patience is the only thing standing between you and the truth of your own name.",
    platforms: ["PS5", "Xbox Series X|S", "PC"],
    anticipated: true,
    hype: 91,
    rating: null,
  },
  {
    id: "game-solstice-overdrive",
    title: "Solstice Overdrive",
    category: "game",
    genres: ["Open World", "Action"],
    releaseDate: "2026-12-05T00:00:00-05:00",
    studio: "Farlight Games",
    description: "An endless summer, a city on the edge of collapse, and a board to ride.",
    synopsis: "Solstice Overdrive is an open-world skating and traversal game set across a fictionalized coastal megacity locked in an artificial eternal summer. Chain grinds, boosts, and vertical exploration through a soundtrack-driven world that reacts to your momentum.",
    platforms: ["PS5", "Xbox Series X|S", "PC", "Switch 2"],
    anticipated: false,
    hype: 68,
    rating: null,
  },
  {
    id: "game-circuit-breakers",
    title: "Circuit Breakers",
    category: "game",
    genres: ["Puzzle", "Co-op"],
    releaseDate: "2027-01-22T00:00:00-05:00",
    studio: "Bramblegate Studio",
    description: "Two minds, one malfunctioning space station, zero margin for error.",
    synopsis: "A tightly-designed two-player puzzle game where you and a partner each control half of a dying space station's systems. Communication is the only tool you have — asymmetric puzzles force real conversation, not just button-matching.",
    platforms: ["PC", "Switch 2"],
    anticipated: false,
    hype: 47,
    rating: null,
  },
  {
    id: "game-obsidian-vale",
    title: "Obsidian Vale",
    category: "game",
    genres: ["Survival", "RPG"],
    releaseDate: "2027-03-06T00:00:00-05:00",
    studio: "Greywatch Interactive",
    description: "A volcanic valley, a dying god, and everything that wants what you carry.",
    synopsis: "From the makers of Ashen Throne, Obsidian Vale is a survival RPG set in a valley cursed by the slow death of an ancient volcanic deity. Craft, build, and negotiate with fellow survivors in a persistent world where the terrain itself is actively trying to kill you.",
    platforms: ["PS5", "Xbox Series X|S", "PC"],
    anticipated: true,
    hype: 82,
    rating: null,
  },
  {
    id: "game-frontier-echo",
    title: "Frontier Echo",
    category: "game",
    genres: ["Space Sim", "Exploration"],
    releaseDate: "2026-07-30T00:00:00-04:00",
    studio: "Lumen Forge",
    description: "Chart the edge of known space before the signal goes quiet for good.",
    synopsis: "Frontier Echo is a slow-burn space exploration sim about a lone surveyor mapping a frontier system that's sending increasingly strange transmissions back home. Minimal combat, maximal atmosphere, and a soundtrack built entirely from processed deep-space radio recordings.",
    platforms: ["PC", "PS5"],
    anticipated: false,
    hype: 58,
    rating: 8.1,
  },
  {
    id: "game-cinderfall",
    title: "Cinderfall",
    category: "game",
    genres: ["Roguelike", "Action"],
    releaseDate: "2026-08-05T00:00:00-04:00",
    studio: "Hollow Anvil",
    description: "Every run burns the world a little more. Some runs, that's the point.",
    synopsis: "Cinderfall is a roguelike where your failed runs permanently scar the map — burned bridges, collapsed passages, and locked-off zones that later runs must route around or reclaim. A punishing, systemic take on the genre with real long-term consequence.",
    platforms: ["PC", "Switch 2", "Xbox Series X|S"],
    anticipated: false,
    hype: 64,
    rating: 8.4,
  },

  // ---------------- MOVIES ----------------
  {
    id: "movie-the-last-signal",
    title: "The Last Signal",
    category: "movie",
    genres: ["Sci-Fi", "Thriller"],
    releaseDate: "2026-08-18T00:00:00-04:00",
    studio: "Meridian Pictures",
    description: "The final transmission from a dying station holds humanity's last answer.",
    synopsis: "When contact is lost with humanity's furthest deep-space relay, a skeleton crew is sent to investigate the final transmission — a signal that shouldn't exist. The Last Signal is a claustrophobic, slow-burn sci-fi thriller about the cost of listening too closely to the dark.",
    platforms: null,
    anticipated: false,
    hype: 70,
    rating: null,
  },
  {
    id: "movie-velvet-horizon",
    title: "Velvet Horizon",
    category: "movie",
    genres: ["Drama"],
    releaseDate: "2026-08-22T00:00:00-04:00",
    studio: "Northlight Films",
    description: "Two estranged sisters, one inherited vineyard, and a summer neither wanted.",
    synopsis: "Velvet Horizon follows two sisters forced to spend one final summer running their late mother's vineyard before selling it. A quiet, character-driven drama about inheritance — the land, the grudges, and everything left unsaid.",
    platforms: null,
    anticipated: false,
    hype: 42,
    rating: null,
  },
  {
    id: "movie-steel-meridian",
    title: "Steel Meridian",
    category: "movie",
    genres: ["Action"],
    releaseDate: "2026-09-25T00:00:00-04:00",
    studio: "Redline Pictures",
    description: "One convoy, one bridge, one hour before it all comes down.",
    synopsis: "A real-time action thriller following a convoy of engineers racing to defuse a bridge collapse orchestrated to cover a much larger heist. Steel Meridian is built around a single unbroken hour of escalating set-pieces.",
    platforms: null,
    anticipated: false,
    hype: 66,
    rating: null,
  },
  {
    id: "movie-hollow-crown",
    title: "Hollow Crown",
    category: "movie",
    genres: ["Fantasy", "Epic"],
    releaseDate: "2026-11-06T00:00:00-05:00",
    studio: "Meridian Pictures",
    description: "The crown chooses its ruler. This year, it chose wrong.",
    synopsis: "Hollow Crown is a sweeping fantasy epic set in the same ashlands mythology as the Ashen Throne games, following the exiled heir to a kingdom whose crown has bound itself to an impostor. Big battles, bigger politics, and a score recorded with a live 90-piece orchestra.",
    platforms: null,
    anticipated: true,
    hype: 93,
    rating: null,
  },
  {
    id: "movie-paper-moonlight",
    title: "Paper Moonlight",
    category: "movie",
    genres: ["Romance"],
    releaseDate: "2026-12-25T00:00:00-05:00",
    studio: "Northlight Films",
    description: "A letter arrives fifteen years late. So does everything else.",
    synopsis: "A misdelivered love letter finally reaches its intended recipient fifteen years after it was written, setting off a gentle, wintry romance about second chances and the versions of ourselves we leave behind.",
    platforms: null,
    anticipated: false,
    hype: 51,
    rating: null,
  },
  {
    id: "movie-midnight-cartographer",
    title: "Midnight Cartographer",
    category: "movie",
    genres: ["Mystery"],
    releaseDate: "2027-01-16T00:00:00-05:00",
    studio: "Driftglass Studios",
    description: "She maps places that don't exist yet. One of them just did.",
    synopsis: "A cartographer who has spent years mapping a fictional city in her sketchbooks discovers a real neighborhood has begun to match her drawings, block by block. A moody, atmospheric mystery about memory, grief, and cities that remember their dead.",
    platforms: null,
    anticipated: false,
    hype: 60,
    rating: null,
  },
  {
    id: "movie-the-glass-orchard",
    title: "The Glass Orchard",
    category: "movie",
    genres: ["Drama"],
    releaseDate: "2027-02-20T00:00:00-05:00",
    studio: "Northlight Films",
    description: "A family orchard, a decade of silence, and the harvest that breaks it.",
    synopsis: "The Glass Orchard reunites a fractured family for one final harvest season at the orchard that raised them. An intimate ensemble drama already generating awards-season buzz for its lead performances.",
    platforms: null,
    anticipated: true,
    hype: 79,
    rating: null,
  },
  {
    id: "movie-echoes-of-tomorrow",
    title: "Echoes of Tomorrow",
    category: "movie",
    genres: ["Sci-Fi"],
    releaseDate: "2026-08-01T00:00:00-04:00",
    studio: "Meridian Pictures",
    description: "Every echo from the future arrives a second before it's true.",
    synopsis: "A physicist begins receiving fragments of tomorrow's news exactly one second before it happens — just long enough to change nothing, and everything. Echoes of Tomorrow is a tight, idea-driven sci-fi drama.",
    platforms: null,
    anticipated: false,
    hype: 57,
    rating: 7.6,
  },
  {
    id: "movie-northern-static",
    title: "Northern Static",
    category: "movie",
    genres: ["Thriller"],
    releaseDate: "2026-07-25T00:00:00-04:00",
    studio: "Redline Pictures",
    description: "A blackout town, a missing radio host, and a signal that keeps talking.",
    synopsis: "When a small northern town goes dark during a record blizzard, the only voice still broadcasting belongs to a radio host who vanished three days earlier. Northern Static is a tense, isolated thriller about the difference between silence and absence.",
    platforms: null,
    anticipated: false,
    hype: 53,
    rating: 7.2,
  },
  {
    id: "movie-crimson-atlas",
    title: "Crimson Atlas",
    category: "movie",
    genres: ["Action", "Spy"],
    releaseDate: "2026-10-09T00:00:00-04:00",
    studio: "Redline Pictures",
    description: "The map to the last cold-war vault was never supposed to be redrawn.",
    synopsis: "A retired cartographer-turned-spy is pulled back in when the map she drew decades ago resurfaces in the hands of the wrong buyer. Crimson Atlas blends globe-trotting spycraft with a very personal reckoning.",
    platforms: null,
    anticipated: false,
    hype: 63,
    rating: null,
  },

  // ---------------- TV SERIES ----------------
  {
    id: "tv-static-age",
    title: "Static Age",
    category: "tv",
    genres: ["Cyberpunk", "Drama"],
    releaseDate: "2026-08-20T00:00:00-04:00",
    studio: "Driftglass Studios",
    description: "In a city run on rationed bandwidth, silence is the real currency.",
    synopsis: "Static Age is set in a near-future city where internet access is rationed by social credit. The series follows a black-market signal broker navigating the city's underbelly one stolen megabyte at a time. Season one, eight episodes.",
    platforms: null,
    anticipated: false,
    hype: 69,
    rating: null,
  },
  {
    id: "tv-the-fracture",
    title: "The Fracture",
    category: "tv",
    genres: ["Mystery", "Drama"],
    releaseDate: "2026-09-05T00:00:00-04:00",
    studio: "Northlight Films",
    description: "The town split in two overnight. Only half remembers why.",
    synopsis: "After a strange geological event splits a small town's memory of a single night into two irreconcilable versions, a detective has to figure out which town is lying — or if both are. A limited mystery series, six episodes.",
    platforms: null,
    anticipated: false,
    hype: 65,
    rating: null,
  },
  {
    id: "tv-ember-and-ash",
    title: "Ember & Ash",
    category: "tv",
    genres: ["Fantasy"],
    releaseDate: "2026-10-17T00:00:00-04:00",
    studio: "Meridian Pictures",
    description: "Two houses. One dying kingdom. A truce built on borrowed time.",
    synopsis: "A prestige fantasy series expanding the world of Hollow Crown, following the uneasy truce between two rival houses forced to share a crumbling capital. Season one adapts the first act of the wider mythology, with ten episodes.",
    platforms: null,
    anticipated: true,
    hype: 85,
    rating: null,
  },
  {
    id: "tv-deep-signal",
    title: "Deep Signal",
    category: "tv",
    genres: ["Sci-Fi"],
    releaseDate: "2026-11-21T00:00:00-05:00",
    studio: "Driftglass Studios",
    description: "First contact happened. Nobody agreed on what it said.",
    synopsis: "Deep Signal follows the fallout of a genuine first-contact event through the eyes of the translators, politicians, and conspiracy theorists all racing to define what was actually said. Season one, eight episodes.",
    platforms: null,
    anticipated: false,
    hype: 72,
    rating: null,
  },
  {
    id: "tv-gaslight-city",
    title: "Gaslight City",
    category: "tv",
    genres: ["Noir", "Crime"],
    releaseDate: "2026-12-12T00:00:00-05:00",
    studio: "Redline Pictures",
    description: "Every streetlamp in this city has a secret. So does everyone under one.",
    synopsis: "A gaslit noir set in a city where the utility company quietly controls who gets to see and who doesn't. Gaslight City follows a lineman-turned-detective investigating a murder that only happened in the dark.",
    platforms: null,
    anticipated: false,
    hype: 59,
    rating: null,
  },
  {
    id: "tv-the-last-cartel",
    title: "The Last Cartel",
    category: "tv",
    genres: ["Crime", "Drama"],
    releaseDate: "2027-01-30T00:00:00-05:00",
    studio: "Redline Pictures",
    description: "The old cartel is gone. What's replacing it is worse.",
    synopsis: "A sprawling crime saga following the power vacuum left after a decades-old cartel finally collapses, and the algorithmic successor organization that rises to take its place. Season one, ten episodes.",
    platforms: null,
    anticipated: false,
    hype: 62,
    rating: null,
  },
  {
    id: "tv-halcyon-drive",
    title: "Halcyon Drive",
    category: "tv",
    genres: ["Road Drama"],
    releaseDate: "2026-08-10T00:00:00-04:00",
    studio: "Northlight Films",
    description: "Four strangers, one borrowed car, and a coastline that won't stay still.",
    synopsis: "Halcyon Drive follows four strangers on a shared road trip down a coastline that keeps changing behind them. Part travelogue, part slow-burn ensemble drama, season one wrapped to strong critical notices.",
    platforms: null,
    anticipated: false,
    hype: 48,
    rating: 8.0,
  },
  {
    id: "tv-nocturne-files",
    title: "Nocturne Files",
    category: "tv",
    genres: ["Detective", "Mystery"],
    releaseDate: "2026-07-28T00:00:00-04:00",
    studio: "Driftglass Studios",
    description: "She only takes cases that happen after midnight.",
    synopsis: "A private investigator who only works the graveyard shift takes on a string of impossible cases that all seem to be connected to a decades-old unsolved disappearance. Season one, seven episodes.",
    platforms: null,
    anticipated: false,
    hype: 56,
    rating: 7.9,
  },
  {
    id: "tv-wildfire-season-2",
    title: "Wildfire — Season 2",
    category: "tv",
    genres: ["Thriller"],
    releaseDate: "2027-02-04T00:00:00-05:00",
    studio: "Redline Pictures",
    description: "The fire's out. The people who started it aren't done.",
    synopsis: "Season two of the acclaimed thriller Wildfire picks up a year after the events of the first season, as the survivors of a suspicious blaze discover it may have been the opening move in something much larger.",
    platforms: null,
    anticipated: false,
    hype: 71,
    rating: null,
  },
  {
    id: "tv-the-departure",
    title: "The Departure",
    category: "tv",
    genres: ["Drama"],
    releaseDate: "2027-03-15T00:00:00-04:00",
    studio: "Meridian Pictures",
    description: "The ship leaves in a year. Nobody on the list wants to go anymore.",
    synopsis: "With humanity's first generation ship set to depart in twelve months, The Departure follows the selected crew as they quietly try to back out of a mission none of them can legally refuse. A slow, tense character drama.",
    platforms: null,
    anticipated: true,
    hype: 81,
    rating: null,
  },

  // ---------------- ANIMATION ----------------
  {
    id: "anim-skybound-legends",
    title: "Skybound Legends",
    category: "animation",
    genres: ["Adventure", "Family"],
    releaseDate: "2026-08-19T00:00:00-04:00",
    studio: "Paperlight Animation",
    description: "A floating archipelago, a broken airship, and a crew of misfits.",
    synopsis: "Skybound Legends follows a ragtag crew of young sky-sailors piecing together a broken airship to reconnect a scattered archipelago of floating islands. Vibrant, painterly animation aimed at all ages. Season one, thirteen episodes.",
    platforms: null,
    anticipated: false,
    hype: 67,
    rating: null,
  },
  {
    id: "anim-paper-constellations",
    title: "Paper Constellations",
    category: "animation",
    genres: ["Animated", "Drama"],
    releaseDate: "2026-09-12T00:00:00-04:00",
    studio: "Paperlight Animation",
    description: "A girl who folds stars from paper meets one that's real.",
    synopsis: "A wordless, hand-painted animated feature about a young girl who folds paper constellations to cope with loss — until one night, a real star answers back. Paper Constellations is being positioned as an awards contender.",
    platforms: null,
    anticipated: true,
    hype: 84,
    rating: null,
  },
  {
    id: "anim-the-tin-forest",
    title: "The Tin Forest",
    category: "animation",
    genres: ["Fantasy", "Animated"],
    releaseDate: "2026-10-30T00:00:00-04:00",
    studio: "Ironleaf Studio",
    description: "A forest built from scrap metal is dying. It needs a new gardener.",
    synopsis: "The Tin Forest follows a scrap-collecting inventor who discovers a forest made entirely of rusting machinery, and the tiny mechanical creatures that call it home. A stop-motion-styled animated feature about repair, patience, and growth.",
    platforms: null,
    anticipated: true,
    hype: 87,
    rating: null,
  },
  {
    id: "anim-junkyard-jubilee",
    title: "Junkyard Jubilee",
    category: "animation",
    genres: ["Comedy", "Family"],
    releaseDate: "2026-11-27T00:00:00-05:00",
    studio: "Ironleaf Studio",
    description: "One junkyard. A thousand tiny robots. Zero adult supervision.",
    synopsis: "A high-energy comedy series following a community of small salvaged robots building an entire secret society inside a junkyard. Season one, twenty-six short episodes.",
    platforms: null,
    anticipated: false,
    hype: 50,
    rating: null,
  },
  {
    id: "anim-moonlit-atlas",
    title: "Moonlit Atlas",
    category: "animation",
    genres: ["Adventure", "Animated"],
    releaseDate: "2026-12-18T00:00:00-05:00",
    studio: "Paperlight Animation",
    description: "A cartographer's daughter inherits a map that draws itself.",
    synopsis: "When her mother disappears, a young cartographer's daughter inherits an atlas that redraws itself each night, leading her toward wherever her mother went. A sweeping, painterly adventure feature.",
    platforms: null,
    anticipated: false,
    hype: 73,
    rating: null,
  },
  {
    id: "anim-glimmer-isles-s3",
    title: "Glimmer Isles — Season 3",
    category: "animation",
    genres: ["Fantasy", "Family"],
    releaseDate: "2027-01-09T00:00:00-05:00",
    studio: "Ironleaf Studio",
    description: "The isles are sinking. The tide waits for no one, not even legends.",
    synopsis: "The beloved Glimmer Isles returns for a third season as the floating isles begin sinking for the first time in a thousand years, forcing the whole cast to finally work together.",
    platforms: null,
    anticipated: false,
    hype: 76,
    rating: null,
  },
  {
    id: "anim-the-clockwork-garden",
    title: "The Clockwork Garden",
    category: "animation",
    genres: ["Fantasy", "Animated"],
    releaseDate: "2027-02-27T00:00:00-05:00",
    studio: "Paperlight Animation",
    description: "A garden that runs on gears instead of seasons is losing time.",
    synopsis: "The Clockwork Garden follows a young gear-smith apprenticed to keep a magical clockwork garden running, right as its central mechanism begins to fail. From the studio behind Paper Constellations.",
    platforms: null,
    anticipated: true,
    hype: 80,
    rating: null,
  },
  {
    id: "anim-starling-and-co",
    title: "Starling & Co.",
    category: "animation",
    genres: ["Comedy", "Slice of Life"],
    releaseDate: "2026-08-03T00:00:00-04:00",
    studio: "Ironleaf Studio",
    description: "A tiny delivery agency run entirely by birds. Deadlines are relative.",
    synopsis: "Starling & Co. follows a small flock running a delivery service out of a converted clocktower, tackling deliveries that always go slightly, charmingly wrong. Season one, twenty episodes.",
    platforms: null,
    anticipated: false,
    hype: 44,
    rating: 7.8,
  },
  {
    id: "anim-driftwood-kingdom",
    title: "Driftwood Kingdom",
    category: "animation",
    genres: ["Adventure", "Animated"],
    releaseDate: "2026-07-22T00:00:00-04:00",
    studio: "Paperlight Animation",
    description: "A kingdom built from shipwrecks, ruled by whoever finds the tide first.",
    synopsis: "Driftwood Kingdom is an animated feature set in a coastal kingdom built entirely from washed-up shipwrecks, following a young scavenger who accidentally becomes heir to a throne made of driftwood.",
    platforms: null,
    anticipated: false,
    hype: 54,
    rating: 8.2,
  },
  {
    id: "anim-nimbus-academy",
    title: "Nimbus Academy",
    category: "animation",
    genres: ["Fantasy", "Coming of Age"],
    releaseDate: "2027-03-20T00:00:00-04:00",
    studio: "Ironleaf Studio",
    description: "A school for storm-riders. Her storm has never once behaved.",
    synopsis: "Nimbus Academy follows a young storm-rider struggling to control an unusually volatile personal storm at the prestigious academy that trains weather-benders. Season one, twelve episodes.",
    platforms: null,
    anticipated: false,
    hype: 58,
    rating: null,
  },
];

/* ---------------------------------------------------------
 * Public data API — swap the internals for real fetch() calls
 * whenever a backend exists. Every function returns a Promise
 * so callers never need to change.
 * ------------------------------------------------------- */
const ReleaseRadarAPI = (() => {
  function fetchItems() {
    // Simulated network latency for realism; replace with:
    // return fetch('/api/items').then(r => r.json());
    return Promise.resolve(RAW_ITEMS.map((i) => ({ ...i })));
  }

  async function getAllItems() {
    return fetchItems();
  }

  async function getItemById(id) {
    const items = await fetchItems();
    return items.find((i) => i.id === id) || null;
  }

  async function getRelatedItems(item, limit = 4) {
    const items = await fetchItems();
    return items
      .filter((i) => i.id !== item.id)
      .map((i) => {
        let score = 0;
        if (i.category === item.category) score += 2;
        score += i.genres.filter((g) => item.genres.includes(g)).length;
        return { item: i, score };
      })
      .filter((x) => x.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((x) => x.item);
  }

  return { getAllItems, getItemById, getRelatedItems };
})();
